---
title: "Parâmetros 2019 Série A"
output: html_notebook
---

```{r, warning = FALSE, message = FALSE}
options(OutDec = ",")
options(knitr.kable.NA = "-")

library(dplyr)
library(knitr)

load("datasets/serie_a_2019.RData")
load("modelos 2019 série A/sol/sol_modelo_0.RData")
load("modelos 2019 série A/sol/sol_modelo_1.RData")
load("modelos 2019 série A/sol/sol_modelo_2.RData")
load("modelos 2019 série A/sol/sol_modelo_3.RData")
load("modelos 2019 série A/sol/sol_modelo_4.RData")
load("modelos 2019 série A/sol/sol_modelo_4b.RData")
load("modelos 2019 série A/sol/sol_modelo_5.RData")
load("modelos 2019 série A/sol/sol_modelo_5b.RData")
```

```{r}
alphas = tibble(Time = times$Time, 
                m0 = sol_modelo_0$pars[1:20],
                m1 = sol_modelo_1$pars[1:20],
                m2 = sol_modelo_2$pars[1:20],
                m3 = sol_modelo_3$pars[1:20],
                m4 = sol_modelo_4$pars[1:20],
                m4b = sol_modelo_4b$pars[1:20],
                m5 = sol_modelo_5$pars[1:20],
                m5b = sol_modelo_5b$pars[1:20]) 
kable(alphas, digits = 4, caption = "Alphas")
```

```{r}
betas = tibble(Time = times$Time, 
               m0 = sol_modelo_0$pars[21:40],
               m1 = sol_modelo_1$pars[21:40],
               m2 = sol_modelo_2$pars[21:40],
               m3 = sol_modelo_3$pars[21:40],
               m4 = sol_modelo_4$pars[21:40],
               m4b = sol_modelo_4b$pars[21:40],
               m5 = sol_modelo_5b$pars[21:40],
               m5b = sol_modelo_5b$pars[21:40]) 
kable(betas, digits = 4, caption = "Betas")
```

```{r}
param = tibble(Modelo = c("0", "1", "2", "3", "4", "4b", "5", "5b"),
               gamma = c(sol_modelo_0$pars[41], sol_modelo_1$pars[41], sol_modelo_2$pars[41],
                         sol_modelo_3$pars[41], sol_modelo_4$pars[41], sol_modelo_4b$pars[41],
                         sol_modelo_5$pars[41], sol_modelo_5b$pars[41]),
               csi_1 = c(NA, NA, sol_modelo_2$pars[42], sol_modelo_3$pars[42], sol_modelo_4$pars[42],
                         sol_modelo_4b$pars[42], sol_modelo_5$pars[42], sol_modelo_5b$pars[42]),
               csi_2 = c(NA, NA, sol_modelo_2$pars[43], sol_modelo_3$pars[43], sol_modelo_4$pars[43],
                         sol_modelo_4b$pars[43], sol_modelo_5$pars[43], sol_modelo_5b$pars[43]),
               ro_1 = c(NA, NA, NA, sol_modelo_3$pars[44], sol_modelo_4$pars[44], sol_modelo_4b$pars[44],
                        sol_modelo_5$pars[44], sol_modelo_5b$pars[44]),
               ro_2 = c(NA, NA, NA, sol_modelo_3$pars[45], sol_modelo_4$pars[45], sol_modelo_4b$pars[45],
                        sol_modelo_5$pars[45], sol_modelo_5b$pars[45]),
               lambda_10 = c(NA, NA, NA, NA, sol_modelo_4$pars[46], sol_modelo_4b$pars[46],
                             sol_modelo_5$pars[46], sol_modelo_5b$pars[46]),
               lambda_01 = c(NA, NA, NA, NA, sol_modelo_4$pars[47], sol_modelo_4b$pars[47],
                             sol_modelo_5$pars[47], sol_modelo_5b$pars[47]),
               lambda_21 = c(NA, NA, NA, NA, NA, NA, sol_modelo_5$pars[48], sol_modelo_5b$pars[48]),
               lambda_12 = c(NA, NA, NA, NA, NA, NA, sol_modelo_5$pars[49], sol_modelo_5b$pars[49]),
               mu_10 = c(NA, NA, NA, NA, sol_modelo_4$pars[48], sol_modelo_4b$pars[48],
                         sol_modelo_5b$pars[50], sol_modelo_5b$pars[50]),
               mu_01 = c(NA, NA, NA, NA, sol_modelo_4$pars[49], sol_modelo_4b$pars[49],
                         sol_modelo_5b$pars[51], sol_modelo_5b$pars[51]),
               mu_21 = c(NA, NA, NA, NA, NA, NA, sol_modelo_5$pars[52], sol_modelo_5b$pars[52]),
               mua_12 = c(NA, NA, NA, NA, NA, NA, sol_modelo_5$pars[53], sol_modelo_5b$pars[53]))
kable(param, digits = 4, caption = "Demais parâmetros")
```

```{r}
veross = tibble(Modelo = c("0", "1", "2", "3", "4", "4b", "5", "5b"),
               log_likelihood = c(sol_modelo_0$values[length(sol_modelo_0$values)],
                                   sol_modelo_1$values[length(sol_modelo_1$values)],
                                   sol_modelo_2$values[length(sol_modelo_2$values)],
                                   sol_modelo_3$values[length(sol_modelo_3$values)],
                                   sol_modelo_4$values[length(sol_modelo_4$values)],
                                   sol_modelo_4b$values[length(sol_modelo_4b$values)],
                                   sol_modelo_5$values[length(sol_modelo_4b$values)],
                                   sol_modelo_5b$values[length(sol_modelo_4b$values)])) %>%
  mutate(log_likelihood = -log_likelihood)
kable(veross, digits = 4, caption = "log Verossimilhanças com os parâmetros encontrados")
```

