---
title: "Parâmetros Rsolnp"
output: html_notebook
---

```{r, warning = FALSE, message = FALSE, echo = FALSE}
options(OutDec = ",")
options(knitr.kable.NA = "-")

library(dplyr)
library(knitr)

load("serie_a_2019.RData")
load("sol/mod_0_glm.RData")
load("sol/mod_0_Rsolnp.RData")
load("sol/mod_1_Rsolnp.RData")
load("sol/mod_2_Rsolnp.RData")
load("sol/mod_3_Rsolnp.RData")
load("sol/mod_4_Rsolnp.RData")
load("sol/mod_5_Rsolnp.RData")
```

```{r, message = FALSE, echo = FALSE}
alphas = tibble(Time = times$Time, 
                glm = c(1, exp(mod_0_glm$coefficients[21:39])),
                mod_0 = mod_0_Rsolnp$pars[1:20],
                mod_1 = mod_1_Rsolnp$pars[1:20],
                mod_2 = mod_2_Rsolnp$pars[1:20],
                mod_3 = mod_3_Rsolnp$pars[1:20],
                mod_4 = mod_4_Rsolnp$pars[1:20],
                mod_5 = mod_5_Rsolnp$pars[1:20])
kable(alphas, digits = 4, caption = "Alphas")
```

```{r, echo = FALSE}
betas = tibble(Time = times$Time, 
               glm = exp(mod_0_glm$coefficients[1:20]),
               mod_0 = mod_0_Rsolnp$pars[21:40],
               mod_1 = mod_1_Rsolnp$pars[21:40],
               mod_2 = mod_2_Rsolnp$pars[21:40],
               mod_3 = mod_3_Rsolnp$pars[21:40],
               mod_4 = mod_4_Rsolnp$pars[21:40],
               mod_5 = mod_5_Rsolnp$pars[21:40])
kable(betas, digits = 4, caption = "Betas")
```

```{r, echo = FALSE}
param = tibble(Modelo = names(alphas)[-1],
               gamma = c(exp(mod_0_glm$coefficients[40]),
                         mod_0_Rsolnp$pars[41], 
                         mod_1_Rsolnp$pars[41],
                         mod_2_Rsolnp$pars[41],
                         mod_3_Rsolnp$pars[41],
                         mod_4_Rsolnp$pars[41],
                         mod_5_Rsolnp$pars[41]),
               csi_1 = c(NA, 
                         NA,
                         NA, 
                         mod_2_Rsolnp$pars[42], 
                         mod_3_Rsolnp$pars[42],
                         mod_4_Rsolnp$pars[42],
                         mod_5_Rsolnp$pars[42]),
               csi_2 = c(NA, 
                         NA, 
                         NA,
                         mod_2_Rsolnp$pars[43], 
                         mod_3_Rsolnp$pars[43],
                         mod_4_Rsolnp$pars[43],
                         mod_5_Rsolnp$pars[43]),
               ro_1 = c(NA, 
                        NA,
                        NA, 
                        NA,
                        mod_3_Rsolnp$pars[44],
                        mod_4_Rsolnp$pars[44],
                        mod_5_Rsolnp$pars[44]),
               ro_2 = c(NA, 
                        NA, 
                        NA, 
                        NA,
                        mod_3_Rsolnp$pars[45],
                        mod_4_Rsolnp$pars[45],
                        mod_5_Rsolnp$pars[45]),
               lambda_10 = c(NA,
                             NA,
                             NA,
                             NA,
                             NA,
                             mod_4_Rsolnp$pars[46],
                             mod_5_Rsolnp$pars[46]),
               lambda_01 = c(NA,
                             NA,
                             NA,
                             NA,
                             NA,
                             mod_4_Rsolnp$pars[47],
                             mod_5_Rsolnp$pars[47]),
               lambda_21 = c(NA,
                             NA,
                             NA,
                             NA,
                             NA,
                             NA,
                             mod_5_Rsolnp$pars[48]),
               lambda_12 = c(NA,
                             NA,
                             NA,
                             NA,
                             NA,
                             NA,
                             mod_5_Rsolnp$pars[49]),
               mu_10 = c(NA,
                         NA,
                         NA,
                         NA,
                         NA,
                         mod_4_Rsolnp$pars[48],
                         mod_5_Rsolnp$pars[50]),
               mu_01 = c(NA,
                         NA,
                         NA,
                         NA,
                         NA,
                         mod_4_Rsolnp$pars[49],
                         mod_5_Rsolnp$pars[51]),
               mu_21 = c(NA,
                         NA,
                         NA,
                         NA,
                         NA,
                         NA,
                         mod_5_Rsolnp$pars[52]),
               mu_12 = c(NA,
                         NA,
                         NA,
                         NA,
                         NA,
                         NA,
                         mod_5_Rsolnp$pars[53]))
kable(param, digits = 4, caption = "Demais parâmetros")
```

```{r, echo = FALSE}
veross = tibble(Modelo = names(alphas)[-c(1,2)],
                log_likelihood = c(-mod_0_Rsolnp$values[length(mod_0_Rsolnp$values)],
                                   -mod_1_Rsolnp$values[length(mod_1_Rsolnp$values)],
                                   -mod_2_Rsolnp$values[length(mod_2_Rsolnp$values)],
                                   -mod_3_Rsolnp$values[length(mod_3_Rsolnp$values)],
                                   -mod_4_Rsolnp$values[length(mod_4_Rsolnp$values)],
                                   -mod_5_Rsolnp$values[length(mod_5_Rsolnp$values)]))
kable(veross, digits = 4, caption = "log Verossimilhanças com os parâmetros encontrados")
```

