---
title: "Goodness of fit"
output: pdf_document
---

```{r, message = FALSE, warning = FALSE}
library(knitr)
library(dplyr)
library(ggplot2)

load("data/goodness_of_fit_dc.RData")
```

```{r}
for(i in 2:nrow(tab_results)) {
  tab_results[i,] = tab_results[i,] - tab_results[1,]
}
kable(tab_results, digits = 4)
```

```{r}
for(i in 2:nrow(tab_results)) {
  tab_home_goals[i,] = tab_home_goals[i,] - tab_home_goals[1,]
}
kable(tab_home_goals, digits = 4)
```

```{r}
for(i in 2:nrow(tab_results)) {
  tab_away_goals[i,] = tab_away_goals[i,] - tab_away_goals[1,]
}
kable(tab_away_goals, digits = 4)
```

\clearpage 

```{r}
tibble(x = c(pars$pred_0$mean_mod_0 - 5 * pars$pred_0$sd_mod_0,
             pars$pred_0$mean_mod_0 + 5 * pars$pred_0$sd_mod_0)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_0$mean_mod_0, sd = pars$pred_0$sd_mod_0)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_0_pred_0, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 0 at minute 0")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_0 - 5 * pars$pred_15$sd_mod_0,
             pars$pred_15$mean_mod_0 + 5 * pars$pred_15$sd_mod_0)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_0, sd = pars$pred_15$sd_mod_0)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_0_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 0 at minute 15")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_30$mean_mod_0 - 5 * pars$pred_30$sd_mod_0,
             pars$pred_30$mean_mod_0 + 5 * pars$pred_30$sd_mod_0)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_30$mean_mod_0, sd = pars$pred_30$sd_mod_0)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_0_pred_30, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 0 at minute 30")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_45$mean_mod_0 - 5 * pars$pred_45$sd_mod_0,
             pars$pred_45$mean_mod_0 + 5 * pars$pred_45$sd_mod_0)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_45$mean_mod_0, sd = pars$pred_45$sd_mod_0)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_0_pred_45, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 0 at minute 45")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_60$mean_mod_0 - 5 * pars$pred_60$sd_mod_0,
             pars$pred_60$mean_mod_0 + 5 * pars$pred_60$sd_mod_0)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_60$mean_mod_0, sd = pars$pred_60$sd_mod_0)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_0_pred_60, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 0 at minute 60")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_75$mean_mod_0 - 5 * pars$pred_75$sd_mod_0,
             pars$pred_75$mean_mod_0 + 5 * pars$pred_75$sd_mod_0)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_75$mean_mod_0, sd = pars$pred_75$sd_mod_0)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_0_pred_75, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 0 at minute 75")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_3 - 5 * pars$pred_15$sd_mod_3,
             pars$pred_15$mean_mod_3 + 5 * pars$pred_15$sd_mod_3)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_3, sd = pars$pred_15$sd_mod_3)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_3_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 3 at minute 0")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_3 - 5 * pars$pred_15$sd_mod_3,
             pars$pred_15$mean_mod_3 + 5 * pars$pred_15$sd_mod_3)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_3, sd = pars$pred_15$sd_mod_3)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_3_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 3 at minute 15")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_30$mean_mod_3 - 5 * pars$pred_30$sd_mod_3,
             pars$pred_30$mean_mod_3 + 5 * pars$pred_30$sd_mod_3)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_30$mean_mod_3, sd = pars$pred_30$sd_mod_3)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_3_pred_30, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 3 at minute 30")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_45$mean_mod_3 - 5 * pars$pred_45$sd_mod_3,
             pars$pred_45$mean_mod_3 + 5 * pars$pred_45$sd_mod_3)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_45$mean_mod_3, sd = pars$pred_45$sd_mod_3)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_3_pred_45, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 3 at minute 45")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_60$mean_mod_3 - 5 * pars$pred_60$sd_mod_3,
             pars$pred_60$mean_mod_3 + 5 * pars$pred_60$sd_mod_3)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_60$mean_mod_3, sd = pars$pred_60$sd_mod_3)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_3_pred_60, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 3 at minute 60")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_75$mean_mod_3 - 5 * pars$pred_75$sd_mod_3,
             pars$pred_75$mean_mod_3 + 5 * pars$pred_75$sd_mod_3)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_75$mean_mod_3, sd = pars$pred_75$sd_mod_3)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_3_pred_75, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 3 at minute 75")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_8 - 5 * pars$pred_15$sd_mod_8,
             pars$pred_15$mean_mod_8 + 5 * pars$pred_15$sd_mod_8)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_8, sd = pars$pred_15$sd_mod_8)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_8_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 8 at minute 0")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_8 - 5 * pars$pred_15$sd_mod_8,
             pars$pred_15$mean_mod_8 + 5 * pars$pred_15$sd_mod_8)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_8, sd = pars$pred_15$sd_mod_8)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_8_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 8 at minute 15")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_30$mean_mod_8 - 5 * pars$pred_30$sd_mod_8,
             pars$pred_30$mean_mod_8 + 5 * pars$pred_30$sd_mod_8)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_30$mean_mod_8, sd = pars$pred_30$sd_mod_8)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_8_pred_30, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 8 at minute 30")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_45$mean_mod_8 - 5 * pars$pred_45$sd_mod_8,
             pars$pred_45$mean_mod_8 + 5 * pars$pred_45$sd_mod_8)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_45$mean_mod_8, sd = pars$pred_45$sd_mod_8)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_8_pred_45, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 8 at minute 45")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_60$mean_mod_8 - 5 * pars$pred_60$sd_mod_8,
             pars$pred_60$mean_mod_8 + 5 * pars$pred_60$sd_mod_8)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_60$mean_mod_8, sd = pars$pred_60$sd_mod_8)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_8_pred_60, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 8 at minute 60")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_75$mean_mod_8 - 5 * pars$pred_75$sd_mod_8,
             pars$pred_75$mean_mod_8 + 5 * pars$pred_75$sd_mod_8)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_75$mean_mod_8, sd = pars$pred_75$sd_mod_8)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_8_pred_75, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 8 at minute 75")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_9 - 5 * pars$pred_15$sd_mod_9,
             pars$pred_15$mean_mod_9 + 5 * pars$pred_15$sd_mod_9)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_9, sd = pars$pred_15$sd_mod_9)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_9_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 9 at minute 0")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_9 - 5 * pars$pred_15$sd_mod_9,
             pars$pred_15$mean_mod_9 + 5 * pars$pred_15$sd_mod_9)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_9, sd = pars$pred_15$sd_mod_9)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_9_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 9 at minute 15")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_30$mean_mod_9 - 5 * pars$pred_30$sd_mod_9,
             pars$pred_30$mean_mod_9 + 5 * pars$pred_30$sd_mod_9)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_30$mean_mod_9, sd = pars$pred_30$sd_mod_9)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_9_pred_30, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 9 at minute 30")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_45$mean_mod_9 - 5 * pars$pred_45$sd_mod_9,
             pars$pred_45$mean_mod_9 + 5 * pars$pred_45$sd_mod_9)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_45$mean_mod_9, sd = pars$pred_45$sd_mod_9)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_9_pred_45, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 9 at minute 45")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_60$mean_mod_9 - 5 * pars$pred_60$sd_mod_9,
             pars$pred_60$mean_mod_9 + 5 * pars$pred_60$sd_mod_9)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_60$mean_mod_9, sd = pars$pred_60$sd_mod_9)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_9_pred_60, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 9 at minute 60")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_75$mean_mod_9 - 5 * pars$pred_75$sd_mod_9,
             pars$pred_75$mean_mod_9 + 5 * pars$pred_75$sd_mod_9)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_75$mean_mod_9, sd = pars$pred_75$sd_mod_9)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_9_pred_75, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 9 at minute 75")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_10 - 5 * pars$pred_15$sd_mod_10,
             pars$pred_15$mean_mod_10 + 5 * pars$pred_15$sd_mod_10)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_10, sd = pars$pred_15$sd_mod_10)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_10_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 10 at minute 0")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_15$mean_mod_10 - 5 * pars$pred_15$sd_mod_10,
             pars$pred_15$mean_mod_10 + 5 * pars$pred_15$sd_mod_10)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_15$mean_mod_10, sd = pars$pred_15$sd_mod_10)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_10_pred_15, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 10 at minute 15")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_30$mean_mod_10 - 5 * pars$pred_30$sd_mod_10,
             pars$pred_30$mean_mod_10 + 5 * pars$pred_30$sd_mod_10)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_30$mean_mod_10, sd = pars$pred_30$sd_mod_10)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_10_pred_30, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 10 at minute 30")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_45$mean_mod_10 - 5 * pars$pred_45$sd_mod_10,
             pars$pred_45$mean_mod_10 + 5 * pars$pred_45$sd_mod_10)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_45$mean_mod_10, sd = pars$pred_45$sd_mod_10)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_10_pred_45, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 10 at minute 45")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_60$mean_mod_10 - 5 * pars$pred_60$sd_mod_10,
             pars$pred_60$mean_mod_10 + 5 * pars$pred_60$sd_mod_10)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_60$mean_mod_10, sd = pars$pred_60$sd_mod_10)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_10_pred_60, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 10 at minute 60")
```

\clearpage 

```{r}
tibble(x = c(pars$pred_75$mean_mod_10 - 5 * pars$pred_75$sd_mod_10,
             pars$pred_75$mean_mod_10 + 5 * pars$pred_75$sd_mod_10)) %>%
  ggplot(aes(x = x)) +
  stat_function(fun = dnorm, n = 10^3, args = list(
    mean = pars$pred_75$mean_mod_10, sd = pars$pred_75$sd_mod_10)) +
  theme_bw() +
  geom_vline(xintercept = loglik_observed_results_mod_10_pred_75, col = "red") +
  xlab("Simulated data") +
  ylab("Count") +
  ggtitle("Results model 10 at minute 75")
```