---
title: "Goodness of fit"
output: pdf_document
---

```{r, message = FALSE, warning = FALSE}
library(knitr)
library(dplyr)
library(ggplot2)
library(stringr)
library(xtable)

options(OutDec = ",")

load("data/goodness_of_fit_dc_3.RData")
```

```{r}
rownames(tab_results) = str_replace_all(rownames(tab_results), "\\s\\(min\\s[0-9]{1,2}\\)", "")

rownames(tab_results)[which(rownames(tab_results) == "Model 12")] = "4"
rownames(tab_results)[which(rownames(tab_results) == "Model 3")] = "3"
rownames(tab_results)[which(rownames(tab_results) == "Model C")] = "2"
rownames(tab_results)[which(rownames(tab_results) == "Model B")] = "1"
rownames(tab_results)[which(rownames(tab_results) == "Model 0")] = "0"
rownames(tab_results)[which(rownames(tab_results) == "Observed")] = "Observado"

Modelo = rownames(tab_results)

tab_results = as.data.frame(tab_results)

Minuto = c("", 
           "", "", "0", "", "",
           "", "", "15", "", "",
           "", "", "30", "", "",
           "", "", "45", "", "",
           "", "", "60", "", "",
           "", "", "75", "", "")

rownames(tab_results) = NULL

tab_results = cbind(Minuto, Modelo, tab_results) %>%
  mutate(Home = round(Home, 4),
         Draw = round(Draw, 4),
         Away = round(Away, 4))
```

```{r}
for(i in 2:nrow(tab_results)) {
  tab_results[i, 3:5] = tab_results[i, 3:5] - tab_results[1, 3:5]
}
kable(tab_results, digits = 4)
```

```{r}
xtable(tab_results, digits = 4)
```

```{r}
rownames(tab_home_goals) = str_replace_all(rownames(tab_home_goals), "\\s\\(min\\s[0-9]{1,2}\\)", "")

rownames(tab_home_goals)[which(rownames(tab_home_goals) == "Model 12")] = "4"
rownames(tab_home_goals)[which(rownames(tab_home_goals) == "Model 3")] = "3"
rownames(tab_home_goals)[which(rownames(tab_home_goals) == "Model C")] = "2"
rownames(tab_home_goals)[which(rownames(tab_home_goals) == "Model B")] = "1"
rownames(tab_home_goals)[which(rownames(tab_home_goals) == "Model 0")] = "0"
rownames(tab_home_goals)[which(rownames(tab_home_goals) == "Observed")] = "Observado"

Modelo = rownames(tab_home_goals)

tab_home_goals = as.data.frame(tab_home_goals)

Minuto = c("", 
           "", "", "0", "", "",
           "", "", "15", "", "",
           "", "", "30", "", "",
           "", "", "45", "", "",
           "", "", "60", "", "",
           "", "", "75", "", "")

rownames(tab_home_goals) = NULL

tab_home_goals = cbind(Minuto, Modelo, tab_home_goals)

tab_home_goals[,3] = round(tab_home_goals[,3], 4)
tab_home_goals[,4] = round(tab_home_goals[,4], 4)
tab_home_goals[,5] = round(tab_home_goals[,5], 4)
tab_home_goals[,6] = round(tab_home_goals[,6], 4)
tab_home_goals[,7] = round(tab_home_goals[,7], 4)
tab_home_goals[,8] = round(tab_home_goals[,8], 4)
```

```{r}
for(i in 2:nrow(tab_results)) {
  tab_home_goals[i, 3:8] = tab_home_goals[i, 3:8] - tab_home_goals[1, 3:8]
}
kable(tab_home_goals, digits = 4)
```

```{r}
xtable(tab_home_goals, digits = 4)
```

```{r}
rownames(tab_away_goals) = str_replace_all(rownames(tab_away_goals), "\\s\\(min\\s[0-9]{1,2}\\)", "")

rownames(tab_away_goals)[which(rownames(tab_away_goals) == "Model 12")] = "4"
rownames(tab_away_goals)[which(rownames(tab_away_goals) == "Model 3")] = "3"
rownames(tab_away_goals)[which(rownames(tab_away_goals) == "Model C")] = "2"
rownames(tab_away_goals)[which(rownames(tab_away_goals) == "Model B")] = "1"
rownames(tab_away_goals)[which(rownames(tab_away_goals) == "Model 0")] = "0"
rownames(tab_away_goals)[which(rownames(tab_away_goals) == "Observed")] = "Observado"

Modelo = rownames(tab_away_goals)

tab_away_goals = as.data.frame(tab_away_goals)

Minuto = c("", 
           "", "", "0", "", "",
           "", "", "15", "", "",
           "", "", "30", "", "",
           "", "", "45", "", "",
           "", "", "60", "", "",
           "", "", "75", "", "")

rownames(tab_away_goals) = NULL

tab_away_goals = cbind(Minuto, Modelo, tab_away_goals)

tab_away_goals[,3] = round(tab_away_goals[,3], 4)
tab_away_goals[,4] = round(tab_away_goals[,4], 4)
tab_away_goals[,5] = round(tab_away_goals[,5], 4)
tab_away_goals[,6] = round(tab_away_goals[,6], 4)
tab_away_goals[,7] = round(tab_away_goals[,7], 4)
tab_away_goals[,8] = round(tab_away_goals[,8], 4)
```

```{r}
for(i in 2:nrow(tab_results)) {
  tab_away_goals[i, 3:8] = tab_away_goals[i, 3:8] - tab_away_goals[1, 3:8]
}
kable(tab_away_goals, digits = 4)
```

```{r}
xtable(tab_away_goals, digits = 4)
```
