---
title: "Generating red cards"
output: pdf_document
---

$$ \lambda_k^*(t) = A_\lambda  t^2$$
$$ \mu_k^*(t) = A_\mu  t^2$$
$$\hat{A_\lambda} = 0.0000003150963$$ 
$$\hat{A_\mu} = 0.0000005093549$$

$$\Lambda^*(t) = \int_0^t \lambda^*(y) dy = A_\lambda \frac{t^3}{3}$$

$$\text{Y}^*(t) = \int_0^t \mu^*(y) dy = A_\mu \frac{t^3}{3}$$

$$\Lambda^{*-1}(t) = \Bigg(\frac{3t}{A_\lambda}\Bigg)^{1/3}$$
$$\text{Y}^{*-1}(t) = \Bigg(\frac{3t}{A_\mu}\Bigg)^{1/3}$$
```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(knitr)

A_lambda = 0.0000003150963
A_mu = 0.0000005093549

inv_lambda <- function(x) {
  (3*x/A_lambda)^(1/3)
}

inv_mu <- function(x) {
  (3*x/A_mu)^(1/3)
}
```

## Generating for the home team in the first half
```{r}
nit = 1000000

home_1st = list()
for(it in 1:nit) {
  t = 0
  s = 0
  tmp = NULL
  while(t < 47) {
    u = runif(1)
    s = s - log(u)
    t = inv_lambda(s)
    if(t < 47) {
      tmp = c(tmp, t)
    }
  }
  home_1st[[it]] = tmp
}
```

## Generating for the away team in the first half
```{r}
away_1st = list()
for(it in 1:nit) {
  t = 0
  s = 0
  tmp = NULL
  while(t < 47) {
    u = runif(1)
    s = s - log(u)
    t = inv_mu(s)
    if(t < 47) {
      tmp = c(tmp, t)
    }
  }
  away_1st[[it]] = tmp
}
```

## Generating for the home team in the second half
```{r}
home_2nd = list()
for(it in 1:nit) {
  t = 0
  s = (1/3)*A_lambda*45^3
  tmp = NULL
  while(t < (49+45)) {
    u = runif(1)
    s = s - log(u)
    t = inv_lambda(s)
    if(t < (49+45)) {
      tmp = c(tmp, t-45)
    }
  }
  home_2nd[[it]] = tmp
}
```

## Generating for the away team in the second half
```{r}
away_2nd = list()
for(it in 1:nit) {
  t = 0
  s = (1/3)*A_mu*45^3
  tmp = NULL
  while(t < (49+45)) {
    u = runif(1)
    s = s - log(u)
    t = inv_mu(s)
    if(t < (49+45)) {
      tmp = c(tmp, t-45)
    }
  }
  away_2nd[[it]] = tmp
}
```

## Comparing the percentage of generated red cards with the real data
```{r}
load("scrape/data/reds.RData")
load("2015-2020/data/input.RData")
Generated = c(length(unlist(home_1st))/nit, length(unlist(away_1st))/nit,
              length(unlist(home_2nd))/nit, length(unlist(away_2nd))/nit,
              length(unlist(home_1st))/nit + length(unlist(away_1st))/nit +
                length(unlist(home_2nd))/nit + length(unlist(away_2nd))/nit)
Real = c(reds %>% filter(Team == 1, Half == 1) %>% nrow() / N,
         reds %>% filter(Team == 2, Half == 1) %>% nrow() / N,
         reds %>% filter(Team == 1, Half == 2) %>% nrow() / N,
         reds %>% filter(Team == 2, Half == 2) %>% nrow() / N,
         nrow(reds)/N)
Team = c("Home", "Away", "Home", "Away", "Both")
Half = c("1st", "1st", "2nd", "2nd", "Both")
tib = tibble(Team, Half, Generated, Real)
kable(tib, digits = 4)
```



