---
title: "Number of simulations"
output: pdf_document
---

```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(ggplot2)
library(future.apply)
plan(multisession(workers = 8))

load("~/GitHub/soccer-live-predictions/soccer-live-predictions/2020/data/mod_0.RData")
load("~/GitHub/soccer-live-predictions/soccer-live-predictions/2020/data/mod_3.RData")
source("pred_mod_0.R")
source("pred_mod_3.R")
```

```{r, eval = FALSE}
n = c(2^c(10:26))
n

m0 = list()
m3 = list()
m0_1_1 = NULL
m0_fla = NULL
m3_1_1 = NULL
m3_fla = NULL

set.seed(1)
for(i in 1:length(n)) {
  m0[[i]] = pred_mod_0(mod_0, n = n[i], home_team = "Flamengo", 
                     away_team = "Internacional")
  m3[[i]] = pred_mod_3(mod_3, n = n[i], home_team = "Flamengo", 
                     away_team = "Internacional")
  m0_1_1[i] = m0[[i]]$Score["1-1"]
  m0_fla[i] = m0[[i]]$Result["Flamengo"]
  m3_1_1[i] = m3[[i]]$Score["1-1"]
  m3_fla[i] = m3[[i]]$Result["Flamengo"]
}

save.image("data/number_of_simulations.RData")
```

```{r, include = FALSE}
load("data/number_of_simulations.RData")
```

\clearpage

```{r}
tibble(n, m0_fla) %>%
  ggplot(aes(x = n, y = m0_fla)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10(breaks = c(10^c(3:8)), labels = paste0("10^", 3:8)) +
  xlab("Number of simulations") +
  ylab("Estimative") +
  theme_bw() +
  ggtitle("Home win, model 0") +
  ylim(0, max(m0_fla))
```

\clearpage

```{r}
tibble(n, m0_fla) %>%
  ggplot(aes(x = n, y = m0_fla)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10(breaks = c(10^c(3:8)), labels = paste0("10^", 3:8)) +
  xlab("Number of simulations") +
  ylab("Estimative") +
  theme_bw() +
  ggtitle("Home win, model 0")
```

\clearpage

```{r}
tibble(n, m3_fla) %>%
  ggplot(aes(x = n, y = m3_fla)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10(breaks = c(10^c(3:8)), labels = paste0("10^", 3:8)) +
  xlab("Number of simulations") +
  ylab("Estimative") +
  theme_bw() +
  ggtitle("Home win, model 3") +
  ylim(0, max(m3_fla))
```

\clearpage

```{r}
tibble(n, m3_fla) %>%
  ggplot(aes(x = n, y = m3_fla)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10(breaks = c(10^c(3:8)), labels = paste0("10^", 3:8)) +
  xlab("Number of simulations") +
  ylab("Estimative") +
  theme_bw() +
  ggtitle("Home win, model 3")
```

\clearpage

```{r}
tibble(n, m0_1_1) %>%
  ggplot(aes(x = n, y = m0_1_1)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10(breaks = c(10^c(3:8)), labels = paste0("10^", 3:8)) +
  xlab("Number of simulations") +
  ylab("Estimative") +
  theme_bw() +
  ggtitle("Score 1-1, model 0") +
  ylim(0, max(m0_1_1))
```

\clearpage

```{r}
tibble(n, m0_1_1) %>%
  ggplot(aes(x = n, y = m0_1_1)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10(breaks = c(10^c(3:8)), labels = paste0("10^", 3:8)) +
  xlab("Number of simulations") +
  ylab("Estimative") +
  theme_bw() +
  ggtitle("Score 1-1, model 0")
```

\clearpage

```{r}
tibble(n, m3_1_1) %>%
  ggplot(aes(x = n, y = m3_1_1)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10(breaks = c(10^c(3:8)), labels = paste0("10^", 3:8)) +
  xlab("Number of simulations") +
  ylab("Estimative") +
  theme_bw() +
  ggtitle("Score 1-1, model 3") +
  ylim(0, max(m3_1_1))
```

\clearpage

```{r}
tibble(n, m3_1_1) %>%
  ggplot(aes(x = n, y = m3_1_1)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10(breaks = c(10^c(3:8)), labels = paste0("10^", 3:8)) +
  xlab("Number of simulations") +
  ylab("Estimative") +
  theme_bw() +
  ggtitle("Score 1-1, model 3")
```

